name: Validate Atlas on Pull Request

on:
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate Atlas Markdown
        uses: pppdns/validate-atlas@main
        with:
          file_path: docs/atlas.md
